apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gemini-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/harsht1608/GenAi_Normal.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gemini-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true