apiVersion: v1
kind: Service
metadata:
  name: gemini-frontend
  namespace: gemini-app
spec:
  selector:
    app: gemini-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer