apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-backend
  labels:
    app: gemini-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini-backend
  template:
    metadata:
      labels:
        app: gemini-backend
    spec:
      containers:
        - name: backend
          image: hashabc/genai_normal-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: gemini-backend-env
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20