apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-frontend
  labels:
    app: gemini-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini-frontend
  template:
    metadata:
      labels:
        app: gemini-frontend
    spec:
      containers:
        - name: frontend
          image: hashabc/genai_normal-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - secretRef:
                name: gemini-frontend-env
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 20