apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hashabc/genai_normal-frontend:latest
        ports:
        - containerPort: 8501
        readinessProbe:
          tcpSocket:
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 20
